const game_data = [
  {
    type: COINS.PER_SECOND,
    cost: 100,
    value: 2,
    name: "Inmate",
    image: "inmate",
  },
  {
    type: COINS.PER_CLICK,
    cost: 100,
    value: 2,
    name: "JedCoin Press",
    image: "press",
  },
  {
    type: COINS.PER_SECOND,
    cost: 750,
    value: 10,
    name: "Workstation",
    image: "workstation",
  },
  {
    type: COINS.PER_SECOND,
    cost: 2000,
    value: 25,
    name: "JedCoin Mine",
    image: "mine",
  },
  {
    type: COINS.PER_SECOND,
    cost: 20000,
    value: 100,
    name: "JedCoin Forge",
    image: "forge",
  },
  {
    type: COINS.PER_SECOND,
    cost: 35000,
    value: 300,
    name: "Jedetically Modified Crop",
    image: "jmocrop",
  },
  {
    type: COINS.PER_CLICK,
    cost: 40000,
    value: 100,
    name: "Jed Clone",
    image: "jedclone",
  },
  {
    type: COINS.PER_SECOND,
    cost: 50000,
    value: 750,
    name: "Nuclear Power Plant",
    image: "powerplant",
  },
  {
    type: COINS.PER_SECOND,
    cost: 100000,
    value: 2000,
    name: "Village",
    image: "village",
  },
  {
    type: COINS.PER_SECOND,
    cost: 1250000,
    value: 15000,
    name: "Space Station",
    image: "spacestation",
  },
  {
    type: COINS.PER_SECOND,
    cost: 2000000,
    value: 50000,
    name: "Moon",
    image: "moon",
  },
  {
    type: COINS.PER_CLICK,
    cost: 7500000,
    value: 5000,
    name: "JeDOS AI",
    image: "jedos",
  },
  {
    type: COINS.PER_SECOND,
    cost: 100000000,
    value: 500000,
    name: "Space Teleporter",
    image: "teleporter",
  },
  {
    type: COINS.PER_CLICK,
    cost: 150000000,
    value: 25000,
    name: "Electromagnetic Coin Magnifier",
    image: "magnet",
  },
  {
    type: COINS.PER_SECOND,
    cost: 500000000,
    value: 1000000,
    name: "Killer Robot",
    image: "robot",
  },
  {
    type: COINS.PER_SECOND,
    cost: 1000000000,
    value: 3000000,
    name: "Dark Matter Coin",
    image: "darkcoin",
  },
  {
    type: COINS.PER_SECOND,
    cost: 2500000000,
    value: 6000000,
    name: "Starship Fleet",
    image: "starship",
  },
  {
    type: COINS.PER_SECOND,
    cost: 7500000000,
    value: 20000000,
    name: "Distant Inhabitable Planet",
    image: "planet",
  },
  {
    type: COINS.PER_SECOND,
    cost: 10000000000,
    value: 80000000,
    name: "Black Hole",
    image: "blackhole",
  },
  {
    type: COINS.PER_SECOND,
    cost: 150000000000,
    value: 200000000,
    name: "Jed Salt",
    image: "jedsalt",
  },
  {
    type: COINS.PER_SECOND,
    cost: 100000000000000,
    value: 30000000000,
    name: "Jed",
    image: "jed",
  },
  {
    type: COINS.PER_SECOND,
    cost: 7,
    value: 0,
    name: "Depressed Cookie",
    image: "cookie",
  },
];
